package com.huawei.user.mapper;

import com.huawei.user.entity.EmergencyGroup;
import com.huawei.user.entity.EmergencyGroupExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmergencyGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    long countByExample(EmergencyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    int deleteByExample(EmergencyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer groupId) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    int insert(EmergencyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    int insertSelective(EmergencyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    List<EmergencyGroup> selectByExample(EmergencyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    EmergencyGroup selectByPrimaryKey(Integer groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EmergencyGroup record, @Param("example") EmergencyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EmergencyGroup record, @Param("example") EmergencyGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmergencyGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emergency_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmergencyGroup record);

    List<EmergencyGroup> listGroup(EmergencyGroup emergencyGroup);

    EmergencyGroup getGroupByUser(String userName);

    List<String> searchGroup(String groupName);
}