server:
  port: 9093
  servlet:
    context-path: /argus-emergency
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  main:
    allow-bean-definition-overriding: true
  freemarker:
    template-loader-path: classpath:/script_template
  application:
    name: emergency-drill
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      auth:
        enabled: true
        username: hujialiang
        password: hujialiang
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/hercules?createDatabaseIfNotExist=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    schema:
      - classpath:create-table.sql
      - classpath:parse_exec_status.sql
      - classpath:parse_scene_exec_status.sql
      - classpath:parse_record_exec_status.sql
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      filter: stat,wall,log4j
      connect-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
    separator: $$$

  #      web-stat-filter:
  #        enabled: true
  #        url-pattern: /*
  #        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
  #      stat-view-servlet:
  #        url-pattern: /druid/*
  #        allow: 127.0.0.1
  #        deny: 192.168.31.253
  #        reset-enable: false
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
   hibernate:
      ddl-auto: update
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.huawei.emergency.mapper
  mapper-locations: classpath*:mapper/*.xml
#用户名
user_name: admin
key: 1234123412341234
decisionEngine.url: http://100.94.174.17:9091/ngrinder-controller-3.4.2
jsch:
  connectTimeout: 30000
  knownHosts: /root/.ssh/known_hosts
  privateKey: /root/.ssh/id_rsa
script:
  location: /tmp/
  timeOut: 300000
  resource:
    uploadPath: D:\tmp
  executor:
    maxTaskSize: 16
    maxSubtaskSize: 8
    blockingTaskSize: 1024
logging:
  level:
    com.huawei.emergency.service: debug
    com.huawei.emergency.schedule: debug
pagehelper:
  reasonable: true
agent:
  name: D:\\tmp\\grinder-http-4.0.0.jar
  uploadPath: /home/emergency/agent/
argus:
  url: http://100.94.169.124:9090/argus
heartbeat:
  readWaitTime: 150
  port: 9100
ngrinder:
  auto:
    execute:
      test: true